name: whiskers
on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Setup Whiskers
        uses: catppuccin/setup-whiskers@v2
      - name: Check
        run: |
          whiskers --check config.json templates/config.tera

  run:
    uses: catppuccin/actions/.github/workflows/whiskers-check.yml@v1
    with:
      args: templates/element.tera
    secrets: inherit
